repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: pelican-s3-backupper
    labels:
      app: pelican-s3-backupper
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    values:
      - values.yaml