image:
  registry: ghcr.io
  repository: tourmalinecore/pelican-s3-backupper
  pullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 256Mi

extraConfigMapEnvVars:
